able_spec_expert:
    resource: "@AbleSpecExpertBundle/Controller/"
    type:     annotation
    prefix:   /    

index:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
able_spec_admin:
    resource: "@AbleSpecAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

# Login
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /account

# override for our homepage
fos_user_security_login:
    path:      /_login
